services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: postgres-rsi-praktikum
    volumes:
      - postgres-data-rsi-praktikum:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build: ./backend
    image: fastapi:latest
    container_name: fastapi-rsi-praktikum
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /app/app
          ignore:
            - __pycache__/
            - '*.pyc'
            - .pytest_cache/
            - tests/
            - '*.log'

        - action: rebuild
          path: ./requirements.txt

        - action: rebuild
          path: ./backend/pyproject.toml

        - action: rebuild
          path: ./backend/uv.lock

        - action: rebuild
          path: ./backend/Dockerfile

        - action: sync
          path: ./backend/.env
          target: /app/.env

        - action: sync
          path: ./backend/alembic.ini
          target: /app/alembic.ini

        - action: sync
          path: ./backend/migrations
          target: /app/migrations
          ignore:
            - __pycache__/
            - '*.pyc'

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: nextjs-rsi-praktikum
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    develop:
      watch:
        - action: sync
          path: ./frontend/app
          target: /app/app
          ignore:
            - node_modules/
            - .next/
        - action: sync
          path: ./frontend/components
          target: /app/components
          ignore:
            - node_modules/
            - .next/
        - action: sync
          path: ./frontend/public
          target: /app/public
        - action: sync
          path: ./frontend/lib
          target: /app/lib
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/Dockerfile.dev
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data-rsi-praktikum:
