services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: postgres-rsi-praktikum
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build: ./backend
    image: fastapi:latest
    container_name: fastapi-rsi-praktikum
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
    ports:
      - "8000:8000"
    networks:
      - internal

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - NEXT_PUBLIC_API_URL=https://rsi-praktikum.prayudahlah.dev/api
    image: nextjs:latest
    container_name: nextjs-rsi-praktikum
    restart: unless-stopped
    ports:
      - "3000:3000"

networks:
  internal:
    driver: bridge


